apiVersion: apps/v1
kind: Deployment
metadata:
	name: auth
spec:
	replicas: 3
	selector:
		matchLabels:
			app: auth
		template:
			metadata:
				labels:
					app: auth
			spec:
				containers:
				- name: orders
					image: voloxatyj/ordering-app_auth
					ports:
						-	containerPort: 3001
					env:
						- name: PORT
							value: '3001'
						-	name: RABBIT_MQ_BILLING_QUEUE
							value: auth
						-	name: RABBIT_MQ_AUTH_QUEU
							value: auth
						-	name: JWT_SECRET
							value: sECret
						-	name: JWT_EXPIRATION
							value: '3600'