apiVersion: apps/v1
kind: Deployment
metadata:
	name: orders
spec:
	replicas: 3
	selector:
		matchLabels:
			app: orders
		template:
			metadata:
				labels:
					app: orders
			spec:
				containers:
				- name: orders
					image: voloxatyj/ordering-app_orders
					ports:
						-	containerPort: 3000
					env:
						-	name: PORT
							value: '3000'
						-	name: RABBIT_MQ_BILLING_QUEUE
							value: auth
						-	name: RABBIT_MQ_AUTH_QUEU
							value: auth